# Generated by Django 3.1.1 on 2020-11-16 21:42

from django.db import migrations, models
from 


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_django', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
